### ISSUE TITLE
ALB SSL policy should be configurable

### ISSUE THREAD

**Issue by gertjanmaas** [philips-software/terraform-aws-ecs-service#4]
The SSL Policy for the ALB Listener is now fixed to `ELBSecurityPolicy-2015-05`.
This should be made configurable, because there are multiple variants.

See https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies for the list of policies.

**Comment by npalm** [comment]
Solved in Release 1.2.0
